/*
Arvancloud PaaS REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paas

import (
	"encoding/json"
)

// checks if the V1RouteIngressCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1RouteIngressCondition{}

// V1RouteIngressCondition RouteIngressCondition contains details for the current condition of this route on a particular router.
type V1RouteIngressCondition struct {
	// RFC 3339 date and time when this condition last transitioned
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`
	// Human readable message indicating details about last transition.
	Message *string `json:"message,omitempty"`
	// (brief) reason for the condition's last transition, and is usually a machine and human readable constant
	Reason *string `json:"reason,omitempty"`
	// Status is the status of the condition. Can be True, False, Unknown.
	Status string `json:"status"`
	// Type is the type of the condition. Currently only Ready.
	Type string `json:"type"`
}

// NewV1RouteIngressCondition instantiates a new V1RouteIngressCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1RouteIngressCondition(status string, type_ string) *V1RouteIngressCondition {
	this := V1RouteIngressCondition{}
	this.Status = status
	this.Type = type_
	return &this
}

// NewV1RouteIngressConditionWithDefaults instantiates a new V1RouteIngressCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1RouteIngressConditionWithDefaults() *V1RouteIngressCondition {
	this := V1RouteIngressCondition{}
	return &this
}

// GetLastTransitionTime returns the LastTransitionTime field value if set, zero value otherwise.
func (o *V1RouteIngressCondition) GetLastTransitionTime() string {
	if o == nil || IsNil(o.LastTransitionTime) {
		var ret string
		return ret
	}
	return *o.LastTransitionTime
}

// GetLastTransitionTimeOk returns a tuple with the LastTransitionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RouteIngressCondition) GetLastTransitionTimeOk() (*string, bool) {
	if o == nil || IsNil(o.LastTransitionTime) {
		return nil, false
	}
	return o.LastTransitionTime, true
}

// HasLastTransitionTime returns a boolean if a field has been set.
func (o *V1RouteIngressCondition) HasLastTransitionTime() bool {
	if o != nil && !IsNil(o.LastTransitionTime) {
		return true
	}

	return false
}

// SetLastTransitionTime gets a reference to the given string and assigns it to the LastTransitionTime field.
func (o *V1RouteIngressCondition) SetLastTransitionTime(v string) {
	o.LastTransitionTime = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V1RouteIngressCondition) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RouteIngressCondition) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V1RouteIngressCondition) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V1RouteIngressCondition) SetMessage(v string) {
	o.Message = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *V1RouteIngressCondition) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RouteIngressCondition) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *V1RouteIngressCondition) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *V1RouteIngressCondition) SetReason(v string) {
	o.Reason = &v
}

// GetStatus returns the Status field value
func (o *V1RouteIngressCondition) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1RouteIngressCondition) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1RouteIngressCondition) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *V1RouteIngressCondition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V1RouteIngressCondition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V1RouteIngressCondition) SetType(v string) {
	o.Type = v
}

func (o V1RouteIngressCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1RouteIngressCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastTransitionTime) {
		toSerialize["lastTransitionTime"] = o.LastTransitionTime
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableV1RouteIngressCondition struct {
	value *V1RouteIngressCondition
	isSet bool
}

func (v NullableV1RouteIngressCondition) Get() *V1RouteIngressCondition {
	return v.value
}

func (v *NullableV1RouteIngressCondition) Set(val *V1RouteIngressCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableV1RouteIngressCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableV1RouteIngressCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1RouteIngressCondition(val *V1RouteIngressCondition) *NullableV1RouteIngressCondition {
	return &NullableV1RouteIngressCondition{value: val, isSet: true}
}

func (v NullableV1RouteIngressCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1RouteIngressCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


