/*
Arvancloud PaaS REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paas

import (
	"encoding/json"
)

// checks if the V1CustomDeploymentStrategyParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CustomDeploymentStrategyParams{}

// V1CustomDeploymentStrategyParams CustomDeploymentStrategyParams are the input to the Custom deployment strategy.
type V1CustomDeploymentStrategyParams struct {
	// Command is optional and overrides CMD in the container Image.
	Command []string `json:"command,omitempty"`
	// Environment holds the environment which will be given to the container for Image.
	Environment []V1EnvVar `json:"environment,omitempty"`
	// Image specifies a Docker image which can carry out a deployment.
	Image *string `json:"image,omitempty"`
}

// NewV1CustomDeploymentStrategyParams instantiates a new V1CustomDeploymentStrategyParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CustomDeploymentStrategyParams() *V1CustomDeploymentStrategyParams {
	this := V1CustomDeploymentStrategyParams{}
	return &this
}

// NewV1CustomDeploymentStrategyParamsWithDefaults instantiates a new V1CustomDeploymentStrategyParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CustomDeploymentStrategyParamsWithDefaults() *V1CustomDeploymentStrategyParams {
	this := V1CustomDeploymentStrategyParams{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *V1CustomDeploymentStrategyParams) GetCommand() []string {
	if o == nil || IsNil(o.Command) {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CustomDeploymentStrategyParams) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *V1CustomDeploymentStrategyParams) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *V1CustomDeploymentStrategyParams) SetCommand(v []string) {
	o.Command = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *V1CustomDeploymentStrategyParams) GetEnvironment() []V1EnvVar {
	if o == nil || IsNil(o.Environment) {
		var ret []V1EnvVar
		return ret
	}
	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CustomDeploymentStrategyParams) GetEnvironmentOk() ([]V1EnvVar, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *V1CustomDeploymentStrategyParams) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given []V1EnvVar and assigns it to the Environment field.
func (o *V1CustomDeploymentStrategyParams) SetEnvironment(v []V1EnvVar) {
	o.Environment = v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *V1CustomDeploymentStrategyParams) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CustomDeploymentStrategyParams) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *V1CustomDeploymentStrategyParams) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *V1CustomDeploymentStrategyParams) SetImage(v string) {
	o.Image = &v
}

func (o V1CustomDeploymentStrategyParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CustomDeploymentStrategyParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	return toSerialize, nil
}

type NullableV1CustomDeploymentStrategyParams struct {
	value *V1CustomDeploymentStrategyParams
	isSet bool
}

func (v NullableV1CustomDeploymentStrategyParams) Get() *V1CustomDeploymentStrategyParams {
	return v.value
}

func (v *NullableV1CustomDeploymentStrategyParams) Set(val *V1CustomDeploymentStrategyParams) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CustomDeploymentStrategyParams) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CustomDeploymentStrategyParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CustomDeploymentStrategyParams(val *V1CustomDeploymentStrategyParams) *NullableV1CustomDeploymentStrategyParams {
	return &NullableV1CustomDeploymentStrategyParams{value: val, isSet: true}
}

func (v NullableV1CustomDeploymentStrategyParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CustomDeploymentStrategyParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


