/*
Arvancloud PaaS REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paas

import (
	"encoding/json"
)

// checks if the V1SourceControlUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SourceControlUser{}

// V1SourceControlUser SourceControlUser defines the identity of a user of source control
type V1SourceControlUser struct {
	// email of the source control user
	Email *string `json:"email,omitempty"`
	// name of the source control user
	Name *string `json:"name,omitempty"`
}

// NewV1SourceControlUser instantiates a new V1SourceControlUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SourceControlUser() *V1SourceControlUser {
	this := V1SourceControlUser{}
	return &this
}

// NewV1SourceControlUserWithDefaults instantiates a new V1SourceControlUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SourceControlUserWithDefaults() *V1SourceControlUser {
	this := V1SourceControlUser{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *V1SourceControlUser) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SourceControlUser) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *V1SourceControlUser) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *V1SourceControlUser) SetEmail(v string) {
	o.Email = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1SourceControlUser) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SourceControlUser) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1SourceControlUser) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1SourceControlUser) SetName(v string) {
	o.Name = &v
}

func (o V1SourceControlUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SourceControlUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableV1SourceControlUser struct {
	value *V1SourceControlUser
	isSet bool
}

func (v NullableV1SourceControlUser) Get() *V1SourceControlUser {
	return v.value
}

func (v *NullableV1SourceControlUser) Set(val *V1SourceControlUser) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SourceControlUser) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SourceControlUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SourceControlUser(val *V1SourceControlUser) *NullableV1SourceControlUser {
	return &NullableV1SourceControlUser{value: val, isSet: true}
}

func (v NullableV1SourceControlUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SourceControlUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


