/*
Arvancloud PaaS REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paas

import (
	"encoding/json"
)

// checks if the V1StepInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1StepInfo{}

// V1StepInfo StepInfo contains details about a build step.
type V1StepInfo struct {
	// durationMilliseconds identifies how long the step took to complete in milliseconds.
	DurationMilliseconds *int64 `json:"durationMilliseconds,omitempty"`
	// name is a unique identifier for each build step.
	Name *string `json:"name,omitempty"`
	// startTime is a timestamp representing the server time when this Step started. it is represented in RFC3339 form and is in UTC.
	StartTime *string `json:"startTime,omitempty"`
}

// NewV1StepInfo instantiates a new V1StepInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1StepInfo() *V1StepInfo {
	this := V1StepInfo{}
	return &this
}

// NewV1StepInfoWithDefaults instantiates a new V1StepInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1StepInfoWithDefaults() *V1StepInfo {
	this := V1StepInfo{}
	return &this
}

// GetDurationMilliseconds returns the DurationMilliseconds field value if set, zero value otherwise.
func (o *V1StepInfo) GetDurationMilliseconds() int64 {
	if o == nil || IsNil(o.DurationMilliseconds) {
		var ret int64
		return ret
	}
	return *o.DurationMilliseconds
}

// GetDurationMillisecondsOk returns a tuple with the DurationMilliseconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StepInfo) GetDurationMillisecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.DurationMilliseconds) {
		return nil, false
	}
	return o.DurationMilliseconds, true
}

// HasDurationMilliseconds returns a boolean if a field has been set.
func (o *V1StepInfo) HasDurationMilliseconds() bool {
	if o != nil && !IsNil(o.DurationMilliseconds) {
		return true
	}

	return false
}

// SetDurationMilliseconds gets a reference to the given int64 and assigns it to the DurationMilliseconds field.
func (o *V1StepInfo) SetDurationMilliseconds(v int64) {
	o.DurationMilliseconds = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1StepInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StepInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1StepInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1StepInfo) SetName(v string) {
	o.Name = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *V1StepInfo) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StepInfo) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *V1StepInfo) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *V1StepInfo) SetStartTime(v string) {
	o.StartTime = &v
}

func (o V1StepInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1StepInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DurationMilliseconds) {
		toSerialize["durationMilliseconds"] = o.DurationMilliseconds
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	return toSerialize, nil
}

type NullableV1StepInfo struct {
	value *V1StepInfo
	isSet bool
}

func (v NullableV1StepInfo) Get() *V1StepInfo {
	return v.value
}

func (v *NullableV1StepInfo) Set(val *V1StepInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableV1StepInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableV1StepInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1StepInfo(val *V1StepInfo) *NullableV1StepInfo {
	return &NullableV1StepInfo{value: val, isSet: true}
}

func (v NullableV1StepInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1StepInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


