/*
Arvancloud PaaS REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paas

import (
	"encoding/json"
)

// checks if the V1ImageImportSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ImageImportSpec{}

// V1ImageImportSpec ImageImportSpec describes a request to import a specific image.
type V1ImageImportSpec struct {
	From V1ObjectReference `json:"from"`
	ImportPolicy *V1TagImportPolicy `json:"importPolicy,omitempty"`
	// IncludeManifest determines if the manifest for each image is returned in the response
	IncludeManifest *bool `json:"includeManifest,omitempty"`
	ReferencePolicy *V1TagReferencePolicy `json:"referencePolicy,omitempty"`
	To *V1LocalObjectReference `json:"to,omitempty"`
}

// NewV1ImageImportSpec instantiates a new V1ImageImportSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ImageImportSpec(from V1ObjectReference) *V1ImageImportSpec {
	this := V1ImageImportSpec{}
	this.From = from
	return &this
}

// NewV1ImageImportSpecWithDefaults instantiates a new V1ImageImportSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ImageImportSpecWithDefaults() *V1ImageImportSpec {
	this := V1ImageImportSpec{}
	return &this
}

// GetFrom returns the From field value
func (o *V1ImageImportSpec) GetFrom() V1ObjectReference {
	if o == nil {
		var ret V1ObjectReference
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *V1ImageImportSpec) GetFromOk() (*V1ObjectReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *V1ImageImportSpec) SetFrom(v V1ObjectReference) {
	o.From = v
}

// GetImportPolicy returns the ImportPolicy field value if set, zero value otherwise.
func (o *V1ImageImportSpec) GetImportPolicy() V1TagImportPolicy {
	if o == nil || IsNil(o.ImportPolicy) {
		var ret V1TagImportPolicy
		return ret
	}
	return *o.ImportPolicy
}

// GetImportPolicyOk returns a tuple with the ImportPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ImageImportSpec) GetImportPolicyOk() (*V1TagImportPolicy, bool) {
	if o == nil || IsNil(o.ImportPolicy) {
		return nil, false
	}
	return o.ImportPolicy, true
}

// HasImportPolicy returns a boolean if a field has been set.
func (o *V1ImageImportSpec) HasImportPolicy() bool {
	if o != nil && !IsNil(o.ImportPolicy) {
		return true
	}

	return false
}

// SetImportPolicy gets a reference to the given V1TagImportPolicy and assigns it to the ImportPolicy field.
func (o *V1ImageImportSpec) SetImportPolicy(v V1TagImportPolicy) {
	o.ImportPolicy = &v
}

// GetIncludeManifest returns the IncludeManifest field value if set, zero value otherwise.
func (o *V1ImageImportSpec) GetIncludeManifest() bool {
	if o == nil || IsNil(o.IncludeManifest) {
		var ret bool
		return ret
	}
	return *o.IncludeManifest
}

// GetIncludeManifestOk returns a tuple with the IncludeManifest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ImageImportSpec) GetIncludeManifestOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeManifest) {
		return nil, false
	}
	return o.IncludeManifest, true
}

// HasIncludeManifest returns a boolean if a field has been set.
func (o *V1ImageImportSpec) HasIncludeManifest() bool {
	if o != nil && !IsNil(o.IncludeManifest) {
		return true
	}

	return false
}

// SetIncludeManifest gets a reference to the given bool and assigns it to the IncludeManifest field.
func (o *V1ImageImportSpec) SetIncludeManifest(v bool) {
	o.IncludeManifest = &v
}

// GetReferencePolicy returns the ReferencePolicy field value if set, zero value otherwise.
func (o *V1ImageImportSpec) GetReferencePolicy() V1TagReferencePolicy {
	if o == nil || IsNil(o.ReferencePolicy) {
		var ret V1TagReferencePolicy
		return ret
	}
	return *o.ReferencePolicy
}

// GetReferencePolicyOk returns a tuple with the ReferencePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ImageImportSpec) GetReferencePolicyOk() (*V1TagReferencePolicy, bool) {
	if o == nil || IsNil(o.ReferencePolicy) {
		return nil, false
	}
	return o.ReferencePolicy, true
}

// HasReferencePolicy returns a boolean if a field has been set.
func (o *V1ImageImportSpec) HasReferencePolicy() bool {
	if o != nil && !IsNil(o.ReferencePolicy) {
		return true
	}

	return false
}

// SetReferencePolicy gets a reference to the given V1TagReferencePolicy and assigns it to the ReferencePolicy field.
func (o *V1ImageImportSpec) SetReferencePolicy(v V1TagReferencePolicy) {
	o.ReferencePolicy = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *V1ImageImportSpec) GetTo() V1LocalObjectReference {
	if o == nil || IsNil(o.To) {
		var ret V1LocalObjectReference
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ImageImportSpec) GetToOk() (*V1LocalObjectReference, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *V1ImageImportSpec) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given V1LocalObjectReference and assigns it to the To field.
func (o *V1ImageImportSpec) SetTo(v V1LocalObjectReference) {
	o.To = &v
}

func (o V1ImageImportSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ImageImportSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	if !IsNil(o.ImportPolicy) {
		toSerialize["importPolicy"] = o.ImportPolicy
	}
	if !IsNil(o.IncludeManifest) {
		toSerialize["includeManifest"] = o.IncludeManifest
	}
	if !IsNil(o.ReferencePolicy) {
		toSerialize["referencePolicy"] = o.ReferencePolicy
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableV1ImageImportSpec struct {
	value *V1ImageImportSpec
	isSet bool
}

func (v NullableV1ImageImportSpec) Get() *V1ImageImportSpec {
	return v.value
}

func (v *NullableV1ImageImportSpec) Set(val *V1ImageImportSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ImageImportSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ImageImportSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ImageImportSpec(val *V1ImageImportSpec) *NullableV1ImageImportSpec {
	return &NullableV1ImageImportSpec{value: val, isSet: true}
}

func (v NullableV1ImageImportSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ImageImportSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


