/*
Arvan VOD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vod

import (
	"encoding/json"
)

// checks if the ChannelsChannelProfilesPostRequestConvertInfoInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelsChannelProfilesPostRequestConvertInfoInner{}

// ChannelsChannelProfilesPostRequestConvertInfoInner struct for ChannelsChannelProfilesPostRequestConvertInfoInner
type ChannelsChannelProfilesPostRequestConvertInfoInner struct {
	// Audio bitrate in kilobit
	AudioBitrate *int32 `json:"audio_bitrate,omitempty"`
	// Video bitrate in kilobit
	VideoBitrate *int32 `json:"video_bitrate,omitempty"`
	// resolution
	Resolution *string `json:"resolution,omitempty"`
}

// NewChannelsChannelProfilesPostRequestConvertInfoInner instantiates a new ChannelsChannelProfilesPostRequestConvertInfoInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelsChannelProfilesPostRequestConvertInfoInner() *ChannelsChannelProfilesPostRequestConvertInfoInner {
	this := ChannelsChannelProfilesPostRequestConvertInfoInner{}
	return &this
}

// NewChannelsChannelProfilesPostRequestConvertInfoInnerWithDefaults instantiates a new ChannelsChannelProfilesPostRequestConvertInfoInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelsChannelProfilesPostRequestConvertInfoInnerWithDefaults() *ChannelsChannelProfilesPostRequestConvertInfoInner {
	this := ChannelsChannelProfilesPostRequestConvertInfoInner{}
	return &this
}

// GetAudioBitrate returns the AudioBitrate field value if set, zero value otherwise.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) GetAudioBitrate() int32 {
	if o == nil || IsNil(o.AudioBitrate) {
		var ret int32
		return ret
	}
	return *o.AudioBitrate
}

// GetAudioBitrateOk returns a tuple with the AudioBitrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) GetAudioBitrateOk() (*int32, bool) {
	if o == nil || IsNil(o.AudioBitrate) {
		return nil, false
	}
	return o.AudioBitrate, true
}

// HasAudioBitrate returns a boolean if a field has been set.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) HasAudioBitrate() bool {
	if o != nil && !IsNil(o.AudioBitrate) {
		return true
	}

	return false
}

// SetAudioBitrate gets a reference to the given int32 and assigns it to the AudioBitrate field.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) SetAudioBitrate(v int32) {
	o.AudioBitrate = &v
}

// GetVideoBitrate returns the VideoBitrate field value if set, zero value otherwise.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) GetVideoBitrate() int32 {
	if o == nil || IsNil(o.VideoBitrate) {
		var ret int32
		return ret
	}
	return *o.VideoBitrate
}

// GetVideoBitrateOk returns a tuple with the VideoBitrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) GetVideoBitrateOk() (*int32, bool) {
	if o == nil || IsNil(o.VideoBitrate) {
		return nil, false
	}
	return o.VideoBitrate, true
}

// HasVideoBitrate returns a boolean if a field has been set.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) HasVideoBitrate() bool {
	if o != nil && !IsNil(o.VideoBitrate) {
		return true
	}

	return false
}

// SetVideoBitrate gets a reference to the given int32 and assigns it to the VideoBitrate field.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) SetVideoBitrate(v int32) {
	o.VideoBitrate = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) GetResolution() string {
	if o == nil || IsNil(o.Resolution) {
		var ret string
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) GetResolutionOk() (*string, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given string and assigns it to the Resolution field.
func (o *ChannelsChannelProfilesPostRequestConvertInfoInner) SetResolution(v string) {
	o.Resolution = &v
}

func (o ChannelsChannelProfilesPostRequestConvertInfoInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelsChannelProfilesPostRequestConvertInfoInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AudioBitrate) {
		toSerialize["audio_bitrate"] = o.AudioBitrate
	}
	if !IsNil(o.VideoBitrate) {
		toSerialize["video_bitrate"] = o.VideoBitrate
	}
	if !IsNil(o.Resolution) {
		toSerialize["resolution"] = o.Resolution
	}
	return toSerialize, nil
}

type NullableChannelsChannelProfilesPostRequestConvertInfoInner struct {
	value *ChannelsChannelProfilesPostRequestConvertInfoInner
	isSet bool
}

func (v NullableChannelsChannelProfilesPostRequestConvertInfoInner) Get() *ChannelsChannelProfilesPostRequestConvertInfoInner {
	return v.value
}

func (v *NullableChannelsChannelProfilesPostRequestConvertInfoInner) Set(val *ChannelsChannelProfilesPostRequestConvertInfoInner) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelsChannelProfilesPostRequestConvertInfoInner) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelsChannelProfilesPostRequestConvertInfoInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelsChannelProfilesPostRequestConvertInfoInner(val *ChannelsChannelProfilesPostRequestConvertInfoInner) *NullableChannelsChannelProfilesPostRequestConvertInfoInner {
	return &NullableChannelsChannelProfilesPostRequestConvertInfoInner{value: val, isSet: true}
}

func (v NullableChannelsChannelProfilesPostRequestConvertInfoInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelsChannelProfilesPostRequestConvertInfoInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


