/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iaas

import (
	"encoding/json"
)

// checks if the CreateVolumeFromSnapshotRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVolumeFromSnapshotRequest{}

// CreateVolumeFromSnapshotRequest struct for CreateVolumeFromSnapshotRequest
type CreateVolumeFromSnapshotRequest struct {
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewCreateVolumeFromSnapshotRequest instantiates a new CreateVolumeFromSnapshotRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVolumeFromSnapshotRequest() *CreateVolumeFromSnapshotRequest {
	this := CreateVolumeFromSnapshotRequest{}
	return &this
}

// NewCreateVolumeFromSnapshotRequestWithDefaults instantiates a new CreateVolumeFromSnapshotRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVolumeFromSnapshotRequestWithDefaults() *CreateVolumeFromSnapshotRequest {
	this := CreateVolumeFromSnapshotRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateVolumeFromSnapshotRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeFromSnapshotRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateVolumeFromSnapshotRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateVolumeFromSnapshotRequest) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateVolumeFromSnapshotRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeFromSnapshotRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateVolumeFromSnapshotRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateVolumeFromSnapshotRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateVolumeFromSnapshotRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVolumeFromSnapshotRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateVolumeFromSnapshotRequest struct {
	value *CreateVolumeFromSnapshotRequest
	isSet bool
}

func (v NullableCreateVolumeFromSnapshotRequest) Get() *CreateVolumeFromSnapshotRequest {
	return v.value
}

func (v *NullableCreateVolumeFromSnapshotRequest) Set(val *CreateVolumeFromSnapshotRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVolumeFromSnapshotRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVolumeFromSnapshotRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVolumeFromSnapshotRequest(val *CreateVolumeFromSnapshotRequest) *NullableCreateVolumeFromSnapshotRequest {
	return &NullableCreateVolumeFromSnapshotRequest{value: val, isSet: true}
}

func (v NullableCreateVolumeFromSnapshotRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVolumeFromSnapshotRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


