/*
ArvanCloud S3 Services

<p/>

API version: 2006-03-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the PutObjectTaggingRequestTagging type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutObjectTaggingRequestTagging{}

// PutObjectTaggingRequestTagging struct for PutObjectTaggingRequestTagging
type PutObjectTaggingRequestTagging struct {
	TagSet Array `json:"TagSet"`
}

// NewPutObjectTaggingRequestTagging instantiates a new PutObjectTaggingRequestTagging object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutObjectTaggingRequestTagging(tagSet Array) *PutObjectTaggingRequestTagging {
	this := PutObjectTaggingRequestTagging{}
	this.TagSet = tagSet
	return &this
}

// NewPutObjectTaggingRequestTaggingWithDefaults instantiates a new PutObjectTaggingRequestTagging object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutObjectTaggingRequestTaggingWithDefaults() *PutObjectTaggingRequestTagging {
	this := PutObjectTaggingRequestTagging{}
	return &this
}

// GetTagSet returns the TagSet field value
func (o *PutObjectTaggingRequestTagging) GetTagSet() Array {
	if o == nil {
		var ret Array
		return ret
	}

	return o.TagSet
}

// GetTagSetOk returns a tuple with the TagSet field value
// and a boolean to check if the value has been set.
func (o *PutObjectTaggingRequestTagging) GetTagSetOk() (*Array, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagSet, true
}

// SetTagSet sets field value
func (o *PutObjectTaggingRequestTagging) SetTagSet(v Array) {
	o.TagSet = v
}

func (o PutObjectTaggingRequestTagging) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutObjectTaggingRequestTagging) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["TagSet"] = o.TagSet
	return toSerialize, nil
}

type NullablePutObjectTaggingRequestTagging struct {
	value *PutObjectTaggingRequestTagging
	isSet bool
}

func (v NullablePutObjectTaggingRequestTagging) Get() *PutObjectTaggingRequestTagging {
	return v.value
}

func (v *NullablePutObjectTaggingRequestTagging) Set(val *PutObjectTaggingRequestTagging) {
	v.value = val
	v.isSet = true
}

func (v NullablePutObjectTaggingRequestTagging) IsSet() bool {
	return v.isSet
}

func (v *NullablePutObjectTaggingRequestTagging) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutObjectTaggingRequestTagging(val *PutObjectTaggingRequestTagging) *NullablePutObjectTaggingRequestTagging {
	return &NullablePutObjectTaggingRequestTagging{value: val, isSet: true}
}

func (v NullablePutObjectTaggingRequestTagging) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutObjectTaggingRequestTagging) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


