/*
ArvanCloud S3 Services

<p/>

API version: 2006-03-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the SelectObjectContentEventStreamStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectObjectContentEventStreamStats{}

// SelectObjectContentEventStreamStats struct for SelectObjectContentEventStreamStats
type SelectObjectContentEventStreamStats struct {
	Details *StatsEventDetails `json:"Details,omitempty"`
}

// NewSelectObjectContentEventStreamStats instantiates a new SelectObjectContentEventStreamStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectObjectContentEventStreamStats() *SelectObjectContentEventStreamStats {
	this := SelectObjectContentEventStreamStats{}
	return &this
}

// NewSelectObjectContentEventStreamStatsWithDefaults instantiates a new SelectObjectContentEventStreamStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectObjectContentEventStreamStatsWithDefaults() *SelectObjectContentEventStreamStats {
	this := SelectObjectContentEventStreamStats{}
	return &this
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *SelectObjectContentEventStreamStats) GetDetails() StatsEventDetails {
	if o == nil || IsNil(o.Details) {
		var ret StatsEventDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelectObjectContentEventStreamStats) GetDetailsOk() (*StatsEventDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *SelectObjectContentEventStreamStats) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given StatsEventDetails and assigns it to the Details field.
func (o *SelectObjectContentEventStreamStats) SetDetails(v StatsEventDetails) {
	o.Details = &v
}

func (o SelectObjectContentEventStreamStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectObjectContentEventStreamStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Details) {
		toSerialize["Details"] = o.Details
	}
	return toSerialize, nil
}

type NullableSelectObjectContentEventStreamStats struct {
	value *SelectObjectContentEventStreamStats
	isSet bool
}

func (v NullableSelectObjectContentEventStreamStats) Get() *SelectObjectContentEventStreamStats {
	return v.value
}

func (v *NullableSelectObjectContentEventStreamStats) Set(val *SelectObjectContentEventStreamStats) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectObjectContentEventStreamStats) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectObjectContentEventStreamStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectObjectContentEventStreamStats(val *SelectObjectContentEventStreamStats) *NullableSelectObjectContentEventStreamStats {
	return &NullableSelectObjectContentEventStreamStats{value: val, isSet: true}
}

func (v NullableSelectObjectContentEventStreamStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectObjectContentEventStreamStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


