/*
ArvanCloud S3 Services

<p/>

API version: 2006-03-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the PutObjectRetentionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutObjectRetentionRequest{}

// PutObjectRetentionRequest struct for PutObjectRetentionRequest
type PutObjectRetentionRequest struct {
	Retention *PutObjectRetentionRequestRetention `json:"Retention,omitempty"`
}

// NewPutObjectRetentionRequest instantiates a new PutObjectRetentionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutObjectRetentionRequest() *PutObjectRetentionRequest {
	this := PutObjectRetentionRequest{}
	return &this
}

// NewPutObjectRetentionRequestWithDefaults instantiates a new PutObjectRetentionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutObjectRetentionRequestWithDefaults() *PutObjectRetentionRequest {
	this := PutObjectRetentionRequest{}
	return &this
}

// GetRetention returns the Retention field value if set, zero value otherwise.
func (o *PutObjectRetentionRequest) GetRetention() PutObjectRetentionRequestRetention {
	if o == nil || IsNil(o.Retention) {
		var ret PutObjectRetentionRequestRetention
		return ret
	}
	return *o.Retention
}

// GetRetentionOk returns a tuple with the Retention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutObjectRetentionRequest) GetRetentionOk() (*PutObjectRetentionRequestRetention, bool) {
	if o == nil || IsNil(o.Retention) {
		return nil, false
	}
	return o.Retention, true
}

// HasRetention returns a boolean if a field has been set.
func (o *PutObjectRetentionRequest) HasRetention() bool {
	if o != nil && !IsNil(o.Retention) {
		return true
	}

	return false
}

// SetRetention gets a reference to the given PutObjectRetentionRequestRetention and assigns it to the Retention field.
func (o *PutObjectRetentionRequest) SetRetention(v PutObjectRetentionRequestRetention) {
	o.Retention = &v
}

func (o PutObjectRetentionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutObjectRetentionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Retention) {
		toSerialize["Retention"] = o.Retention
	}
	return toSerialize, nil
}

type NullablePutObjectRetentionRequest struct {
	value *PutObjectRetentionRequest
	isSet bool
}

func (v NullablePutObjectRetentionRequest) Get() *PutObjectRetentionRequest {
	return v.value
}

func (v *NullablePutObjectRetentionRequest) Set(val *PutObjectRetentionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutObjectRetentionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutObjectRetentionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutObjectRetentionRequest(val *PutObjectRetentionRequest) *NullablePutObjectRetentionRequest {
	return &NullablePutObjectRetentionRequest{value: val, isSet: true}
}

func (v NullablePutObjectRetentionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutObjectRetentionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


